/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


public class App {


    public static void main(String[] args) {

//        For test database
//        try {
//            PgDatabase db = new PgDatabase();
//        } catch (Exception e) {
//            System.out.println("Error: " + e.getMessage());
//            e.printStackTrace();
//        }

//        For testing meals_db
//        try {
//            MealsDb db = new MealsDb();
//        } catch (Exception e) {
//            System.out.println("Error: " + e.getMessage());
//            e.printStackTrace();
//        }



        AppService service = new AppService();
        TextUI ui = new TextUI(service);
        ui.start();

    }
}
